{% set name = "uproot" %}
{% set version = "3.5.2" %}

package:
  name: {{ name }}-base
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 677f228c7abf107a72ecc3e94973f8babd2a171a04b6c4ffdbf7fb9cd9a00dc4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - numpy >=1.13.1
    - awkward >=0.9.0
    - uproot-methods >=0.5.0
    - cachetools

test:
  imports:
    - {{ name }}

outputs:
  - name: {{ name }}-base

  - name: {{ name }}
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage(name+'-base', exact=True) }}
        - backports.lzma  # [py27]
        - lz4
        - requests
        - xrootd  # [unix]
    test:
      imports:
        - uproot

about:
  home: https://github.com/scikit-hep/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'ROOT I/O in pure Python and Numpy.'
  description: |
    uproot (originally μproot, for “micro-Python ROOT”) is a reader and a writer
    of the ROOT file format using only Python and Numpy. Unlike the standard C++
    ROOT implementation, uproot is only an I/O library, primarily intended to
    stream data into machine learning libraries in Python. Unlike PyROOT and
    root_numpy, uproot does not depend on C++ ROOT. Instead, it uses Numpy calls
    to rapidly cast data blocks in the ROOT file as Numpy arrays.
  dev_url: https://github.com/scikit-hep/{{ name }}
  doc_url: https://{{ name }}.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - chrisburr
    - jpivarski
