travis:
  secure:
    BINSTAR_TOKEN: JxMjYt5IsaXJrU2729PfEiCL0tWusxM2/fHb9vcwSTnzKBEFMw+gLYWWwdn6eZ6CrAyBWq3WSddPy7fbmnGEL7sTGayXfkzvXq0fJuaE4vM69vSsU9WvPMY6jOdbNy6SXDXxxI/wsqfUGI4LZDsZsfFwb0MlX2+JaJHczvABwgrgfV4sYxc+9Kxb8BjDorXz8/Hf03uJdh0awb1nuOFHDEZYowUQVmrzv/aRxQvwCFZmP+QKq+KifiXTqs0zroAs4cV1bzP2GCoaiRt5lEVENNHo6wnquDG1acQeSk/t0TE0uM0KGZwwIZdPGEmczQJxHh+9v9cvmdbOJ7DHBJfk4zxOzxqPvTaU2bF/T2699HrRB1AXp+lNdzYBEKRUZmlM+E/3/SWm9sWVbDWz7uX1lrOZ3XlkKvGQWZAJSO4S/TBpJ5CRH4f4GjHaHhrXge9fB8QuJinz2P4JGKryJee0IREhW9Dc+z3wRU0trOuzrJHmF84zQYyOFQkMQ7yEk2ucok9u0ftfpj9PaYpGPrrfMhO9K/9wTPUu3QGrsM85SpQzCPi322h2ebZQe8F4Vky67wUlr2ZVbv6PNarMgtmL24Rr491ffh3Ikr0JEjDXBjsvxl+Ix43EuxcrbSMaiULITJqeofSWXdeXZpcGn/leerqfMiatjcPjPdFZuNvySrg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
